name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Build Release
        run: zig build -Doptimize=ReleaseSafe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fuze-${{ runner.os }}
          path: zig-out/bin/fuze*
          if-no-files-found: error
