name: Nightly Release

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

permissions:
  contents: write
  packages: write
  actions: write

env:
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_OWNER: ${{ github.repository_owner }}
  GITHUB_REPO: ${{ github.event.repository.name }}

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for code changes
        id: check
        run: |
          # Get the latest nightly release tag
          LATEST_NIGHTLY=$(git tag -l "*-nightly.*" | sort -V | tail -n1 || echo "")
          
          if [ -z "$LATEST_NIGHTLY" ]; then
            # No previous nightly release exists
            echo "No previous nightly release found. Running release."
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            # Check for changes in code files since last nightly
            CHANGES=$(git diff --name-only $LATEST_NIGHTLY...HEAD -- '*.zig' '*.ts' '*.js' '*.py' || echo "")
            
            if [ -n "$CHANGES" ]; then
              echo "Changes detected since last nightly release:"
              echo "$CHANGES"
              echo "should_run=true" >> $GITHUB_OUTPUT
            else
              echo "No code changes since last nightly release."
              echo "should_run=false" >> $GITHUB_OUTPUT
            fi
          fi

  nightly:
    needs: check_changes
    if: needs.check_changes.outputs.should_run == 'true'
    runs-on: ubuntu-latest  # Use a specific runner for consistency

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Installation Scripts
        run: python3 .github/scripts/build_scripts.py
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Set Up Git Config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Cache tree-sitter dependencies
        uses: actions/cache@v3
        with:
          path: deps/tree-sitter
          key: ${{ runner.os }}-tree-sitter-${{ hashFiles('deps/tree-sitter/**') }}
          restore-keys: |
            ${{ runner.os }}-tree-sitter-

      - name: Cache tree-sitter-typescript dependencies
        uses: actions/cache@v3
        with:
          path: deps/tree-sitter-typescript
          key: ${{ runner.os }}-tree-sitter-typescript-${{ hashFiles('deps/tree-sitter-typescript/**') }}
          restore-keys: |
            ${{ runner.os }}-tree-sitter-typescript-

      - name: Clone tree-sitter
        if: steps.cache-tree-sitter-dependencies.outputs.cache-hit != 'true'
        run: |
          mkdir -p deps
          git clone --depth 1 --branch v0.20.8 https://github.com/tree-sitter/tree-sitter.git deps/tree-sitter

      - name: Clone tree-sitter-typescript
        if: steps.cache-tree-sitter-typescript-dependencies.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch v0.20.1 https://github.com/tree-sitter/tree-sitter-typescript.git deps/tree-sitter-typescript

      - name: Generate Nightly Version
        id: versioning
        run: |
          # Try to get the latest stable version from tags, fallback to build.zig.zon version if no tags exist
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "")
          if [ -z "$LATEST_TAG" ]; then
            # No tags exist, use version from build.zig.zon
            LATEST_VERSION=$(grep '\.version = ' build.zig.zon | cut -d'"' -f2)
            echo "No tags found, using version from build.zig.zon: ${LATEST_VERSION}"
          else
            LATEST_VERSION=${LATEST_TAG#v}
            echo "Found latest tag version: ${LATEST_VERSION}"
          fi

          # Validate the version format
          if ! python3 -c "import re; import sys; sys.exit(0 if re.match(r'^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$', '$LATEST_VERSION') else 1)"; then
            echo "Error: Latest version $LATEST_VERSION is not a valid semver (MAJOR.MINOR.PATCH)"
            exit 1
          fi

          # Get current date
          CURRENT_DATE=$(date +%Y%m%d)

          # Create nightly version
          NIGHTLY_VERSION="${LATEST_VERSION}-nightly.${CURRENT_DATE}"

          # Validate the nightly version format
          if ! python3 -c "import re; import sys; sys.exit(0 if re.match(r'^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)-nightly\.\d{8}$', '$NIGHTLY_VERSION') else 1)"; then
            echo "Error: Nightly version $NIGHTLY_VERSION is not valid"
            exit 1
          fi

          echo "NIGHTLY_VERSION=${NIGHTLY_VERSION}" >> $GITHUB_ENV
          echo "Generated nightly version: ${NIGHTLY_VERSION}"

      - name: Update build.zig.zon with Nightly Version
        run: |
          python3 .github/scripts/update_version.py build.zig.zon "${NIGHTLY_VERSION}"

      - name: Commit and Push build.zig.zon
        run: |
          git add build.zig.zon
          git commit -m "chore: update build.zig.zon to nightly version ${NIGHTLY_VERSION}"
          git push

      - name: Run Tests
        run: zig build test

      - name: Build Nightly Release
        run: zig build -Doptimize=ReleaseSafe

      - name: Create Nightly Release
        uses: ncipollo/release-action@v1
        with:
          tag: nightly-${{ env.NIGHTLY_VERSION }}
          name: Nightly Release ${{ env.NIGHTLY_VERSION }}
          draft: false
          prerelease: true

      - name: Upload Release Asset (Linux)
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./zig-out/bin/fuze-linux-x64
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset (macOS)
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./zig-out/bin/fuze-macos-x64
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset (Windows)
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./zig-out/bin/fuze-windows-x64.exe
          token: ${{ secrets.GITHUB_TOKEN }}
